version: 2.1
orbs:
  python: circleci/python@1.0.0
jobs:
  build:
    docker:
      - image: circleci/python:3.8.6
    steps:
      - checkout
      - run: mkdir test-results
      - run: python Test.py
      - run: python HelloCircleCi.py
      - store_test_results:
          path: test-results